//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Booking
    {
        public long Id { get; set; }
        public Nullable<System.DateTime> BookingDate { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<long> ProductId { get; set; }
        public Nullable<int> CustomerId { get; set; }
        public Nullable<int> AddressId { get; set; }
    
        public virtual Account Account { get; set; }
        public virtual ShippingAddress ShippingAddress { get; set; }
        public virtual Product Product { get; set; }
    }
}
